db.schema.name: books

spring:
  main:
    banner-mode: 'off'
  # ===============================
  # = VIRTUAL THREADS
  # ===============================
  threads:
    virtual:
      enabled: true
  # ===============================
  # = DATASOURCE
  # ===============================
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
    hikari:
      schema: ${db.schema.name}
  # ===============================
  # = LIQUIBASE
  # ===============================
  liquibase:
    enabled: true
    default-schema: ${db.schema.name}
    change-log: classpath:db/changelog/db.changelog.yml
  # ===============================
  # = JOOQ
  # ===============================
  jooq:
    sql-dialect: postgres
# ===============================
# = ACTUATOR
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: '*'
# ===============================
# = SERVER
# ===============================
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /service
# ===============================
# = LOGGING
# ===============================
logging:
  level:
    root: info
    sql: info
    web: info
